spring.application.name=Food-Health-Classifier
server.port= 8080


razorpay.key.id=rzp_test_S7himHMdfujbzL
razorpay.key.secret=03A9esutmbG2F73mopyQS01h

spring.datasource.url=jdbc:mysql://localhost:3306/food_classifier_db
spring.datasource.username=root
spring.datasource.password=Parmeshwar1@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
